#include <v8.h>
#include <unistd.h>
#include "runtime.h"


// generated by autoconf
#include "../binjs_config.h"
#include "../../../bash-4.3/version.h"

using namespace v8;


Handle<Value> RuntimeV8Version(const Arguments& args) {
	HandleScope scope;
	
	return String::New(V8::GetVersion());
}


Handle<Value> RuntimeBashVersion(const Arguments& args) {
	HandleScope scope;
	
	return String::New(DISTVERSION);
}

Handle<Value> RuntimeBinjsVersion(const Arguments& args) {
	HandleScope scope;
	
	return String::New(PACKAGE_VERSION);
}

Handle<Value> RuntimeIsATTY(const Arguments& args) {
	HandleScope scope;
	
	return Boolean::New(isatty(STDIN_FILENO) && isatty(STDOUT_FILENO) );
}

